### ISSUE TITLE
any papers of the idea?

### ISSUE THREAD

**Issue by jeannotes** [a-price/MCMC#1]
Hi, I just find this amazing package, and I am really interested, can I have further instructions of this package codes?

really thanks.

**Comment by a-price** [comment]
Hi @jeannotes, this was some code from a class project at GT with Frank Dellaert. It's quite rough, as I was pretty new to both the math and Boost at the time, so I probably wouldn't recommend using it for anything very critical. If you're interested in the idea, this might be some good reading: https://smartech.gatech.edu/handle/1853/44944
